# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbd77423445e9cb7e2efec966f4b2fcfa7c8d8ca46635087831137824b895b5777665a7baa643a3e3fa26e78cbd771d2b91a1c85a2aab82354bd662232aaaa31

test:
  secret_key_base: 0d5651412938931c18857d55fc8ab6279e8b6e67a799700c3e994dd491ae189233a25dd28955400ce89d2f8516ef9b5b8a2038079681fb48adb4c5e81c62184c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
